server:
  port: 5000

spring:
  datasource:
    url: jdbc:mysql://my01.everleap.com/MySQL_2177_inventory
    driverClassName: com.mysql.jdbc.Driver
    username: lovepacsdb
    password: lovepacsPW
    max-active: 2
    max-idle: 2
    min-idle: 1
    initial-size: 1

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

security:
  basic.enabled: false

logging:
  level.org.springframework.security: INFO