server:
  port: 5000

spring:
  datasource:
    url: jdbc:mysql://us-cdbr-iron-east-03.cleardb.net/heroku_1f5e834167eaa5a
    driverClassName: com.mysql.jdbc.Driver
    username: b7b896ec17b621
    password: e8b9ee85

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

security:
  basic.enabled: false

logging:
  level.org.springframework.security: INFO