server:
  port: 5000

spring:
  datasource:
    url: jdbc:mysql://url
    driverClassName: com.mysql.jdbc.Driver
    username: username
    password: password

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none